### ISSUE TITLE
return all offsprings in recombinators

### ISSUE THREAD

**Issue by surmann** [jakobbossek/ecr#101]
The recombinators (crossover and pmx) return only one of their offsprings. We should return a list of all offsprings.

**Comment by surmann** [comment]
done

**Comment by surmann** [comment]
First idea in commit 31e931c.

**Comment by surmann** [comment]
Probably better: function with arbitrary number of arguments `makeChildren(...)`.

**Comment by jakobbossek** [comment]
Added a function `wrapChildren` as proposed by me today. It eventually wraps the children in a list and appends the logical `multiple` attribute to it.
