### ISSUE TITLE
Generators ignore 'requires' and 'forbidden'

### ISSUE THREAD

**Issue by surmann** [jakobbossek/ecr#103]
All generators ignore the `requires` argument in e.g. `makeIntegerVectorParam` and the `forbidden` argument in `makeParamSet`.

**Comment by surmann** [comment]
We need a deeper invention in the code to make this run properly.
A redefinition of the individuals is necessary. An individual will be a list of genes, one gene for every parameter (vector)

**Comment by surmann** [comment]
I implemented the first for binary representation in the branch `multiParam`. You find the example `onesAndZeros_example.R` in the example directory.

A short feedback would be fine.

**Comment by surmann** [comment]
I change the understanding of an individual in the following way:
If one parameter is defined in the parameter set, a list element of the population is the realisation of the parameter.
If many parameter are defined, an individual is a list with realisations of each parameter.

**Comment by surmann** [comment]
If `require` or `forbidden` are used throw a warning.

**Comment by surmann** [comment]
Write helper function to convert 1d list to atomic.

**Comment by jakobbossek** [comment]
Now a warning is produced in `makeOptimizationTask` if the parameters of the passed smoof function has requirements or forbidden regions. Closing this for now.

**Comment by jakobbossek** [comment]
Sorry, not closing. We are going to handle this in a later release.

**Comment by jakobbossek** [comment]
Closing this for now. To generate a population of feasible-only solutions, one has to write its own generator.
