### ISSUE TITLE
Definition of an individual and the population

### ISSUE THREAD

**Issue by surmann** [jakobbossek/ecr#122]
Currently, an `individual` is a vector element of the list `population`. Individuals that are a list itself are currently not supported, the user has to define its own methods (generator, mutator, ...).

I think we should stay with this approach and add an example with complexer individuals later. What do you think?

**Comment by jakobbossek** [comment]
Actually there is already [an rather artificial example](https://github.com/jakobbossek/ecr/blob/master/inst/examples/custom_example.R) with each individual being a matrix. However, I already thought about wrapping each individual within an `ecr_individual` S3 object. This way we could attach more attributes to the individuals like age/dob and stuff like that.

**Comment by surmann** [comment]
In this example an individual is one object, in this case a matrix. But what, if you have two matrices as one individual as a list? In this case, the function `computeFitness` and other will fail.

[Here](https://github.com/jakobbossek/ecr/blob/master/inst/examples/onesAndZeros_example.R) is an example for this case. Commit ed7f2a5c24cda6357a3b92afb4f118ab5587a334 solves the problem in `computeFitness` and related functions.

**Comment by jakobbossek** [comment]
You really need to check the tests! On the master branch the travis build button should always be green.
This is done now.
