### ISSUE TITLE
Internal restructuring

### ISSUE THREAD

**Issue by jakobbossek** [jakobbossek/ecr#125]
Doing some heavy internal restructuring at the moment:
* selectors now always return the indizes of the selected, currently active individuals instead of constructing a populuation each time
* OptPath is used to store the entire population. Dob and eol are used the right way now

**Comment by jakobbossek** [comment]
Argh, that sucks! Multi-objective stuff is much faster now, but single-objective is in increasingly slow. Reason: computation of the next generation is cheap, but updating the opt path is expensive.

**Comment by berndbischl** [comment]
Like I said, specialize the OP a bit in PH. Or code the add-Op in C. The former cannot be so hard, if you base it on a matrix.

**Comment by jakobbossek** [comment]
Selectors now work on fitness only and do not return a part of the population.
Opt.path is used to store the best / non-dominated individuals for now. Closing.
