### ISSUE TITLE
Parameter definition available twice

### ISSUE THREAD

**Issue by surmann** [jakobbossek/ecr#128]
The result of `doTheEvolution` contains the parameter definition twice. It is available in `result$control$par.upper` and `...$par.lower`, and in `result$opt.path$par.set`.

Do we have an advantage thereof?

**Comment by jakobbossek** [comment]
The par.set was internally appended to the control object to be available everywhere (control is passed down). Now the optimization task now takes this role. However, par.set is always part of the opt.path as well. It is kind of redundant, but an unimportant point. Closing this.
