### ISSUE TITLE
autoplot(res)

### ISSUE THREAD

**Issue by berndbischl** [jakobbossek/ecr#130]
1) Why not get together and use the plotter from PH?
Make it better (even needed?),  then call a customized version from ecr?

2) Unit test it with a custom example! There seems to be a gug.
```
> autoplot(res)
Error in UseMethod("getNumberOfParameters") : 
  no applicable method for 'getNumberOfParameters' applied to an object of class "function"
```

**Comment by jakobbossek** [comment]
Fixed the bug. Closing this. We are going to talk about the ecr PH relation in #142.
