### ISSUE TITLE
CI crap

### ISSUE THREAD

**Issue by jakobbossek** [jakobbossek/ecr#156]
```

+ echo 'Installing GitHub packages: jakobbossek/smoof'
Installing GitHub packages: jakobbossek/smoof
+ Rscript -e 'library(devtools); library(methods); options(repos=c(CRAN="https://cran.rstudio.com")); install_github(commandArgs(TRUE), build_vignettes = FALSE)' jakobbossek/smoof
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo jakobbossek/smoof@master
from URL https://api.github.com/repos/jakobbossek/smoof/zipball/master
Error in download(dest, src, auth) : Unauthorized (HTTP 401).
Calls: install_github ... remote_download.github_remote -> download -> <Anonymous>
Execution halted
Command exited with code 1
```

**Comment by jakobbossek** [comment]
I really hate TravisCI/Appveyor. Spending more time trying to figure out non package or R related stuff that breaks the build the actually developing interesting stuff.
Now there is this crap:
```
travis_time:end:160b8325:start=1465323606121013274,finish=1465323610520377079,duration=4399363805
[0Ktravis_time:start:16d28dce
[0K$ tar xzf /tmp/texlive.tar.gz -C ~

travis_time:end:16d28dce:start=1465323610524923262,finish=1465323612711242691,duration=2186319429
[0K$ export PATH=/$HOME/texlive/bin/x86_64-linux:$PATH
travis_time:start:12291000
[0K$ tlmgr update --self
Unknown directive ...containerchecksum c59200574a316416a23695c258edf3a32531fbda43ccdc09360ee105c3f07f9fb77df17c4ba4c2ea4f3a5ea6667e064b51e3d8c2fe6c984ba3e71b4e32716955... , please fix it! at /home/travis/texlive/tlpkg/TeXLive/TLPOBJ.pm line 210, <$retfh> line 5579.

travis_time:end:12291000:start=1465323612716199631,finish=1465323614384847535,duration=1668647904
[0K
[31;1mThe command "tlmgr update --self" failed and exited with 25 during .[0m

Your build has been stopped.
```
Going to ignore the red button for a while 😠

**Comment by berndbischl** [comment]
did you google it?
https://www.tug.org/pipermail/tex-live/2016-May/038505.html

**Comment by jakobbossek** [comment]
Yes, but I do not feel like fixing it at the moment.

**Comment by berndbischl** [comment]
well it looks like your R install already fails. when texlive is installed.
if this would be the case, travis would be broken for everybody who uses R with it on github? 

restart your travis build and i will trigger also one of my own.

**Comment by jakobbossek** [comment]
Already restarted the builds multiple times for two repositories. Always failing on the linux machines.
I guess your rebuild will also fail.

**Comment by berndbischl** [comment]
i does indeed. then we need to open up an issue. nobody will be able to work properly otherwise.....

**Comment by jakobbossek** [comment]
Going to do this tomorrow. I have no nerves to do this now. A lot of other things are in the pipeline now.

**Comment by berndbischl** [comment]
was reported 10 min ago

https://github.com/craigcitro/r-travis/issues/174

**Comment by jakobbossek** [comment]
Ok. Good.

**Comment by jakobbossek** [comment]
Travis is fine now and appveyor is fixed.
