### ISSUE TITLE
Same dimensionality in computeAverageHausdorffDistance

### ISSUE THREAD

**Issue by danielhorn** [jakobbossek/ecr#171]
Hi Jakob,

in computeAverageHausdorffDistance  you have

`  if (nrow(A) != nrow(B)) {
    stopf("Sets A and B need to have the same dimensionality.")
  }`

Why? You need ncol(A) = ncol(B), i.e. the same number of targets, but the number of rows (observations) can be different for the distance?

Daniel

**Comment by jakobbossek** [comment]
The matrix in ecr is always in column major format, i.e., each column is an individual.

**Comment by jakobbossek** [comment]
This is much easier to work with in C.

**Comment by danielhorn** [comment]
Then you have a bug in your Docu :) In the docu of computeGenerationalDistance you say that each row is a point:
`#' @param A [\code{matrix}]\cr
#'   First point set (each row corresponds to a point).`

**Comment by jakobbossek** [comment]
Ah. I see. Thanks.

**Comment by jakobbossek** [comment]
Fixed via 6263522
