### ISSUE TITLE
Possible bug when configuring evalutionary operator

### ISSUE THREAD

**Issue by kerschke** [jakobbossek/ecr#178]
Hi,

I presume there might be a bug within `getDefaultEvolutionaryOperators`. The reason for that is that I receive an error, when running the following example:

```{r}
library(smoof)
onemax = makeSingleObjectiveFunction(
  name = "One-Max",
  fn = function(x) length(x) - sum(x),
  par.set = makeParamSet(
    makeIntegerVectorParam(len = 50, id = "x", lower = 0, upper = 1)
  )
)

ctrl = setupECRControl(
  n.population = 1L,
  n.offspring = 1L,
  n.mating.pool = 1L,
  representation = "binary",
  survival.strategy = "plus",
  logger = setupOptPathLoggingMonitor(),
  stopping.conditions = list(
    setupMaximumIterationsTerminator(max.iter = 1000L)
  )
)

ctrl = setupEvolutionaryOperators(
  ctrl,
  mutator = setupBitFlipMutator(p = 1 / 50),
  recombinator = setupNullRecombinator()
)

res = doTheEvolution(onemax, control = ctrl)
Initialization finished! Starting optimization process ...
Fehler in sample.int(x, size, replace, prob) : 
  kann keine Stichprobe größer als die Grundgesamtheit nehmen
 wenn 'replace = FALSE'
```

Tracing back the error lead me to `getDefaultEvolutionaryOperators` and when checking your previous commits, I saw that you changed `"parent.selector" = setupRouletteWheelSelector()` to `"parent.selector" = setupTournamentSelector(k = 2L)`. However, if I change it back to `"parent.selector" = setupRouletteWheelSelector()` (at least for the binary case), `doTheEvolution` runs just fine..

**Comment by jakobbossek** [comment]
Thanks for reporting. This was due to a small bug in the k-tournament selector. Fixed.
