### ISSUE TITLE
Possible broken monitors (or outdated documentation)

### ISSUE THREAD

**Issue by larsbe** [jakobbossek/ecr#179]
When trying to execute ecr/inst/examples/smoof_example.R, the following error occurs:

`Error in makeMonitor(step = myMonitorStep) : 
  Assertion on 'step' failed: Must have formal arguments: opt.state,....`

These assertions are also not documented in the respective function documentation (ecr/R/makeMonitor.R).

When trying to change the function's signature to match the assertions, setting up the ecr control object fails with the following error:

`Error in setupECRControl(n.population = 10L, n.offspring = 10L, survival.strategy = "plus",  : 
  Assertion on 'fun' failed: Must have first formal arguments (ordered): opt.state,....`

Any ideas how to fix this?

**Comment by jakobbossek** [comment]
Thanks! Indeed the example and docs for `makeMonitor` were outdated. Fixed via 8b53352.
