### ISSUE TITLE
We need tests

### ISSUE THREAD

**Issue by jakobbossek** [jakobbossek/ecr#33]
A lot of stuff is not tested automatically. Think of meaningful test cases and write a lot of tests!

**Comment by jakobbossek** [comment]
Write tests for permutation based and binary algorithms next.

**Comment by surmann** [comment]
What should a test for the permutation generator contain?
* check used numbers for every chromosom
* set seed and check permutation against standard `sample` implementation
* ...

**Comment by surmann** [comment]
I add a first test for the permutation generator. What do you think?

**Comment by jakobbossek** [comment]
I rather thought of solving a small permutation based problem with ecr's permutation based operators and check the solution for optimality. See test_ecr.R for similar tests for other representations :wink: 

But we should test all aspects of ecr, i.e., the small building blocks as well. This test is helpful for sure :+1:

**Comment by jakobbossek** [comment]
I just recognized that you copied some stuff from the permutationGenerator to the test case, set the same seed two times and checked for equality. This is no test, since you compare with the implementation which might contain some kind of programming. On this special case you should check whether the result is a permutation.

**Comment by jakobbossek** [comment]
I already rewrote the test.

**Comment by jakobbossek** [comment]
We now have tests which cover the most important parts.
