### ISSUE TITLE
Allow arbitrary representations

### ISSUE THREAD

**Issue by jakobbossek** [jakobbossek/ecr#66]
At the moment we allow `float`, `binary` and `permutation` as representation types. Moreover we store the population as a numeric matrix. This is a convenient way, but we cannot handle mixed spaces this way. Moreover, individuals are limited to be atomic vectors. There should be the possibility to operate on arbitrary represenations.

**Comment by jakobbossek** [comment]
This is the most important aspect. Need to invest some time in this soon.

**Comment by jakobbossek** [comment]
There are some aspects we need to think about intensively:

* To allow arbitrary objects we need the most flexible representation for single individuals. I guess the best choice is a `list` object with the list elements being the single target function parameters. For simple numeric optimization task this would be the parameters values, but it may be a single matrix as well.

* Until now everything is based on `ParamSet` and `Opt.path` objects. However, these can only describe scalar or vectorized values, but no data.frames, matrizes, lists or arbitrary S3 objects we would later like to operate on. How to take this into consideration? Bypass all this stuff if the representation is set to custom? But how to save the optimization progress in this case? We could definitely save at least the target values in the opt.path beside execution time and stuff like that.

**Comment by surmann** [comment]
1. Is it the best way to chose a `list` object every time? How time consuming is a `list` compared to a `matrix`, if a `matrix` does the job? Probably in most cases a `matrix` will represent the given problem.

**Comment by jakobbossek** [comment]
Currently investing a lot if time in this.

**Comment by jakobbossek** [comment]
Just a note to myself: we cannot use the opt path to save e.g. matrices. Thus, I will introduce a dummy parameter set to be able to use the opt path at all. Not the best solution, but I do not see an alternative satisfying approach since stuff like the stopping condition mechanism is based on the opt.path.

**Comment by jakobbossek** [comment]
Done for now. Added stupid example in inst/examples/.
