### ISSUE TITLE
Additional value of "mutator.control" and "recombinator.control"

### ISSUE THREAD

**Issue by surmann** [jakobbossek/ecr#71]
"ecr.control" differs between "mutator" and "mutator.control" ("recombinator" and "recombinator.control" respectively).
What is the additional value of "mutator.control", if one can set a parameter directly with "mutator = makeBitFlipMutator(0.01)"?

**Comment by jakobbossek** [comment]
I did this for multiple reasons:
1. Possibility to store the operator parameters in the optimization path. For this I needed the names, default values and stuff like inside the ecr function.
2. Possibility to manipulate parameters in each iteration before passing them to the operator
3. Have the possibility to globally check operator parameters during the construction of the ecr control object.

However, setting the parameters directly would result in a nicer interface. Actually I could ask the operator for the needed information via some helper methods.

**Comment by jakobbossek** [comment]
Removed `mutator.control` and `recombinator.control`.
