### ISSUE TITLE
use e.g. "gen." as prefix for "save.population.at"

### ISSUE THREAD

**Issue by surmann** [jakobbossek/ecr#72]
"save.population.at = c(0L, 10L)" results in storing generation 0 and 10 in "res$population.storage". The generations are accessible by "res$population.storage[["0"]]" or "res$population.storage$'10'", obviously not by "res$population.storage$0". A prefix like "gen." would solve this problem and give a convenient access like "res$population.storage$gen.0".

**Comment by jakobbossek** [comment]
Good idea :smiley:
Done.
