### ISSUE TITLE
Mult-objective emoa quality indicators

### ISSUE THREAD

**Issue by jakobbossek** [jakobbossek/ecr#83]
Collection of issues: We need
* hypervolume indicator
* R{1,2,3} indicator
* epsilon indicator
* ...

**Comment by berndbischl** [comment]
Look at emoa / mco first. There is C code in there, which was also copied in by Olaf. Should be directly reusable.

**Comment by jakobbossek** [comment]
Yeah, I already glanced at the code some time ago.

**Comment by jakobbossek** [comment]
Done
