### ISSUE TITLE
Multi-criteria optimization

### ISSUE THREAD

**Issue by jakobbossek** [jakobbossek/ecr#9]
The package shall offer a toolset/framework for mono-objective as well as multi-criteria objective functions. Think about how to separate that. Do we need `optim.mono` and `optim.multi` funs or can we handle all the stuff with one fun?

**Comment by surmann** [comment]
Very interesting. Unique compared to GA.

**Comment by jakobbossek** [comment]
Yeah, but this is a long way to go :-)
If you want to tackle some multi-objective problems with evolutionary multi-objective algorithms in R at the moment take a look at the packages [emoa](http://cran.r-project.org/web/packages/emoa/index.html) and [mco](http://cran.r-project.org/web/packages/mco/index.html).

**Comment by jakobbossek** [comment]
With the current operator interface and the internal structure and data types used in ecr it is not difficult to enable multi-objective evolutionary optimization. At the moment I am already working on it.

**Comment by jakobbossek** [comment]
Merged the *multiobjective* branch into the master branch. Multi-objective is now possible. Still all the operators are missing. See the other issues for that.
